name: Generate Snake Gif

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch: # Allows manual trigger

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: BALAVIGNESHWARAN23
          outputs: dist/snake.svg

      - name: Upload Snake Gif
        uses: actions/upload-artifact@v3
        with:
          name: github-contribution-grid-snake
          path: dist/snake.svg

      - name: Commit and Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          mv dist/snake.svg output/github-contribution-grid-snake.gif
          git add output/github-contribution-grid-snake.gif
          git commit -m "Generated contribution snake gif"
          git push
